server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jlottery
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  file:
    name: log_file.log
    path: ./